apiVersion: v1
entries:
  kubeflower:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-14T17:39:52.358689786+02:00"
    description: Helm chart for KubeFlower - Federated Learning with Flower on Kubernetes
    digest: 4d038c18b5313f189c230a37d07d71ffbf38d6d62f393d77540c2fd45360db02
    home: https://github.com/adap/flower
    keywords:
    - federated-learning
    - flower
    - kubernetes
    - gnn
    - machine-learning
    maintainers:
    - name: Group 3 Team
    name: kubeflower
    sources:
    - https://flower.ai/
    type: application
    urls:
    - kubeflower-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-14T17:39:52.35668563+02:00"
    description: Helm chart for KubeFlower - Federated Learning with Flower on Kubernetes
    digest: 5b1b4d46881732537ccec3ed1448d1fcb8d2f3267d106d1d57bccc5d5aa43211
    home: https://github.com/adap/flower
    keywords:
    - federated-learning
    - flower
    - kubernetes
    - gnn
    - machine-learning
    maintainers:
    - name: Group 3 Team
    name: kubeflower
    sources:
    - https://flower.ai/
    type: application
    urls:
    - kubeflower-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-14T17:39:52.355651565+02:00"
    description: Helm chart for KubeFlower - Federated Learning with Flower on Kubernetes
    digest: 77558713f72e7d9f0a600e76358b079c0c90b1504575b89b6ba71792eff8d981
    home: https://github.com/adap/flower
    keywords:
    - federated-learning
    - flower
    - kubernetes
    - gnn
    - machine-learning
    maintainers:
    - name: Group 3 Team
    name: kubeflower
    sources:
    - https://flower.ai/
    type: application
    urls:
    - kubeflower-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-14T17:39:52.354588306+02:00"
    description: Helm chart for KubeFlower - Federated Learning with Flower on Kubernetes
    digest: 3b328bdb6d99ca76b3ecf7dd63d8659fe966342faed4ea6618ec981736180a8a
    home: https://github.com/adap/flower
    keywords:
    - federated-learning
    - flower
    - kubernetes
    - gnn
    - machine-learning
    maintainers:
    - name: Group 3 Team
    name: kubeflower
    sources:
    - https://flower.ai/
    type: application
    urls:
    - kubeflower-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-14T17:39:52.353534267+02:00"
    description: Helm chart for KubeFlower - Federated Learning with Flower on Kubernetes
    digest: 77d8d7b60fa9132373207608e3d28c9d86abe76185de270d7da6876467de7215
    home: https://github.com/adap/flower
    keywords:
    - federated-learning
    - flower
    - kubernetes
    - gnn
    - machine-learning
    maintainers:
    - name: Group 3 Team
    name: kubeflower
    sources:
    - https://flower.ai/
    type: application
    urls:
    - kubeflower-0.1.0.tgz
    version: 0.1.0
generated: "2026-04-14T17:39:52.352231244+02:00"
